### ISSUE TITLE
Not connecting to 5zig servers.

### ISSUE THREAD

**Issue by Rayn322** [5zig/The-5zig-Mod#11]

**Comment by ghost** [comment]
did u fix it ?

**Comment by Rayn322** [comment]
No. Is it not connecting for you too?

**Comment by ghost** [comment]
you need to join the server but the server isn't Available soo wtf lol

**Comment by Rayn322** [comment]
It should connect upon starting the game.

**Comment by ghost** [comment]
um

**Comment by oShottyBoi** [comment]
doesnt work for me either, tried to get a cape but cant

**Comment by JSR-Gaming-x** [comment]
5zig quit, shutdown the website, shutdown the servers (required for the capes to work) and redirected the domain to this github page.

**Comment by Movion** [comment]
rip. bye 5zig

**Comment by Jump-Suit** [comment]
NOOOOOOO.......

**Comment by Jump-Suit** [comment]
I actually Used this mod for friends list across servers! That really sucks!
